categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '💣 Breaking Change'
    label: 'Breaking Change'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🔨 Maintenance'
    label: 'maintenance'
template: |
  ## Getting GoGin
  Read the documentation at README
  ## New in GoGin v$NEXT_PATCH_VERSION
  $CHANGES
