version: '3.8'
services:

  backend:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - fullstack-postgres
    environment:
      WAIT_HOSTS: postgres:5432
    restart: on-failure
    network_mode: host

  fullstack-postgres:
    restart: always
    image: "postgres:12"
    environment:
      POSTGRES_USER: goland
      POSTGRES_PASSWORD: goland
      POSTGRES_DB: goland
    volumes:
      - ./deployments/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    network_mode: host

volumes:
  postgresql: