version: "3.8"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: gogin-grafana
    network_mode: "bridge"
    depends_on:
      - prometheus
      - prometheus-pushgateway
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: gogin-prometheus
    network_mode: "bridge"
  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: gogin-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"