version: '3.8'
services:

  backend:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    networks:
      - overlay
    ports:
      - 8082:8082
    depends_on:
      - fullstack-postgres
    environment:
      WAIT_HOSTS: postgres:5432
    restart: on-failure

  fullstack-postgres:
    restart: always
    image: "postgres:13.3"
    healthcheck:
      test: psql postgres --command "select 1"
    environment:
      POSTGRES_USER: goland
      POSTGRES_PASSWORD: goland
      POSTGRES_DB: goland
    volumes:
      - ./deployments/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql:/var/lib/postgresql
    networks:
      - overlay
    ports:
      - 5432:5432

  broker_app:
    image: dius/pact-broker
    ports:
      - "9080:80"
    links:
      - fullstack-postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: goland
      PACT_BROKER_DATABASE_PASSWORD: goland
      PACT_BROKER_DATABASE_HOST: fullstack-postgres
      PACT_BROKER_DATABASE_NAME: goland

volumes:
  postgresql:

networks:
  overlay:
    driver: bridge