apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
  - image: gogin-api
deploy:
  helm:
    releases:
    - name: gogin-api
      chartPath: deployments/helmchart
      artifactOverrides:
        image: gogin-api