on: [push]

jobs:
  Performance_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker compose
        run: docker-compose up -d
      - name: Run cloud performance test
        uses: k6io/action@v0.2.0
        with:
          filename: performance/tests/perf_login_test.js
          cloud: false
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}