on: [push]

jobs:
  Performance_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup NewRelic Agent
        run: |
          docker run \
            -d --restart unless-stopped \
            --name newrelic-statsd \
            -h $(hostname) \
            -e NR_ACCOUNT_ID=${{secrets.NR_ACCOUNTID}} \
            -e NR_API_KEY=${{secrets.NR_APIKEY}} \
            -e NR_EU_REGION=true \
            -e NR_LOG_METRICS=true \
            -e TAGS="k6Test:PerformanceTest" \
            -p 8125:8125/udp \
            newrelic/nri-statsd:latest
      - name: Docker compose application
        run: docker-compose up -d
      - name: Download and Installing K6 ...
        run: |
          curl https://github.com/k6io/k6/releases/download/v0.32.0/k6-v0.32.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
      - name: Run Performance test
        run: K6_STATSD_ENABLE_TAGS=true ./k6 run --out statsd performance/tests/perf_login_test.js
        env:
          NR_APIKEY: {{secrets.NR_APIKEY}}